"""empty message

Revision ID: 1560213b0364
Revises: 5c19326f0acb
Create Date: 2021-08-19 16:30:53.772631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1560213b0364'
down_revision = '5c19326f0acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('takesCare',
    sa.Column('idFollows', sa.Integer(), nullable=False),
    sa.Column('idTreatment', sa.Integer(), nullable=False),
    sa.Column('ciPa', sa.Integer(), nullable=False),
    sa.Column('ciMp', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ciMp'], ['medicalPersonnel.ci'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idFollows', 'idTreatment', 'ciPa'], ['follows.idFollows', 'follows.idTreatment', 'follows.ciPa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idFollows', 'idTreatment', 'ciPa', 'ciMp', 'date')
    )
    op.drop_table('takes_care')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('takes_care',
    sa.Column('idFollows', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idTreatment', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ciPa', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ciMp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ciMp'], ['medicalPersonnel.ci'], name='takes_care_ciMp_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idFollows', 'idTreatment', 'ciPa'], ['follows.idFollows', 'follows.idTreatment', 'follows.ciPa'], name='takes_care_idFollows_idTreatment_ciPa_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idFollows', 'idTreatment', 'ciPa', 'ciMp', 'date', name='takes_care_pkey')
    )
    op.drop_table('takesCare')
    # ### end Alembic commands ###
