"""empty message

Revision ID: 9193421a48d3
Revises: ba50812ee767
Create Date: 2021-08-19 14:26:02.145983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9193421a48d3'
down_revision = 'ba50812ee767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apTakesPlace',
    sa.Column('idAp', sa.Integer(), nullable=False),
    sa.Column('idBranch', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idAp'], ['appointment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idBranch'], ['branch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idAp', 'idBranch')
    )
    op.create_table('apRefPrevAp',
    sa.Column('idCurrAp', sa.Integer(), nullable=False),
    sa.Column('idPrevAp', sa.Integer(), nullable=False),
    sa.Column('ciPaCurrAp', sa.Integer(), nullable=False),
    sa.Column('ciPaPrevAp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ciPaCurrAp'], ['patient.ci'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ciPaPrevAp'], ['patient.ci'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idCurrAp'], ['appointment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idPrevAp'], ['appointment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idCurrAp', 'idPrevAp', 'ciPaCurrAp', 'ciPaPrevAp')
    )
    op.create_table('diagnoses',
    sa.Column('idAp', sa.Integer(), nullable=False),
    sa.Column('ciPa', sa.Integer(), nullable=False),
    sa.Column('idDis', sa.Integer(), nullable=False),
    sa.Column('detail', sa.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['ciPa'], ['patient.ci'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idAp'], ['appointment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idDis'], ['clinicalSign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idAp', 'ciPa', 'idDis')
    )
    op.create_table('registersCs',
    sa.Column('idAp', sa.Integer(), nullable=False),
    sa.Column('ciPa', sa.Integer(), nullable=False),
    sa.Column('idCs', sa.Integer(), nullable=False),
    sa.Column('detail', sa.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['ciPa'], ['patient.ci'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idAp'], ['appointment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idCs'], ['clinicalSign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idAp', 'ciPa', 'idCs')
    )
    op.create_table('registersSy',
    sa.Column('idAp', sa.Integer(), nullable=False),
    sa.Column('ciPa', sa.Integer(), nullable=False),
    sa.Column('idSy', sa.Integer(), nullable=False),
    sa.Column('detail', sa.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['ciPa'], ['patient.ci'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idAp'], ['appointment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idSy'], ['symptom.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idAp', 'ciPa', 'idSy')
    )
    op.create_table('assistsAp',
    sa.Column('idAp', sa.Integer(), nullable=False),
    sa.Column('ciPa', sa.Integer(), nullable=False),
    sa.Column('ciMa', sa.Integer(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['ciMa'], ['medicalAssistant.ci'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ciPa'], ['patient.ci'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idAp'], ['appointment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idAp', 'ciPa', 'ciMa', 'time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistsAp')
    op.drop_table('registersSy')
    op.drop_table('registersCs')
    op.drop_table('diagnoses')
    op.drop_table('apRefPrevAp')
    op.drop_table('apTakesPlace')
    # ### end Alembic commands ###
