"""empty message

Revision ID: af53d7feb117
Revises: 
Create Date: 2021-08-15 23:24:09.238687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af53d7feb117'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('CI', sa.Integer(), nullable=False),
    sa.Column('name1', sa.String(length=32), nullable=False),
    sa.Column('name2', sa.String(length=32), nullable=True),
    sa.Column('surname1', sa.String(length=32), nullable=False),
    sa.Column('surname2', sa.String(length=32), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('genre', sa.String(length=16), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('CI')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
