"""empty message

Revision ID: e6581c9b3aec
Revises: 
Create Date: 2021-08-16 20:10:56.814063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6581c9b3aec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('preview', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('question',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('specialty',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('CI', sa.Integer(), nullable=False),
    sa.Column('name1', sa.VARCHAR(length=32), nullable=False),
    sa.Column('name2', sa.VARCHAR(length=32), nullable=True),
    sa.Column('surname1', sa.VARCHAR(length=32), nullable=False),
    sa.Column('surname2', sa.VARCHAR(length=32), nullable=True),
    sa.Column('sex', sa.CHAR(length=1), nullable=False),
    sa.Column('genre', sa.VARCHAR(length=32), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=256), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('CI')
    )
    op.create_table('administrative',
    sa.Column('CI', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CI'], ['user.CI'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CI')
    )
    op.create_table('from',
    sa.Column('IDQ', sa.Integer(), nullable=False),
    sa.Column('IDF', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IDF'], ['form.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['IDQ'], ['question.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('IDQ', 'IDF')
    )
    op.create_table('medicalPersonnel',
    sa.Column('CI', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CI'], ['user.CI'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CI')
    )
    op.create_table('patient',
    sa.Column('CI', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CI'], ['user.CI'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CI')
    )
    op.create_table('userPhone',
    sa.Column('CI', sa.Integer(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['CI'], ['user.CI'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CI', 'phone')
    )
    op.create_table('designed',
    sa.Column('CIMP', sa.Integer(), nullable=False),
    sa.Column('IDF', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('isMainAuthor', sa.BOOLEAN(), nullable=False),
    sa.Column('changelog', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['CIMP'], ['medicalPersonnel.CI'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['IDF'], ['form.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CIMP', 'IDF', 'date')
    )
    op.create_table('doctor',
    sa.Column('CI', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CI'], ['medicalPersonnel.CI'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CI')
    )
    op.create_table('medicalAssistant',
    sa.Column('CI', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CI'], ['medicalPersonnel.CI'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CI')
    )
    op.create_table('mpHasSpec',
    sa.Column('CIMp', sa.Integer(), nullable=False),
    sa.Column('IDSpec', sa.Integer(), nullable=False),
    sa.Column('detail', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['CIMp'], ['medicalPersonnel.CI'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['IDSpec'], ['specialty.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CIMp', 'IDSpec')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mpHasSpec')
    op.drop_table('medicalAssistant')
    op.drop_table('doctor')
    op.drop_table('designed')
    op.drop_table('userPhone')
    op.drop_table('patient')
    op.drop_table('medicalPersonnel')
    op.drop_table('from')
    op.drop_table('administrative')
    op.drop_table('user')
    op.drop_table('specialty')
    op.drop_table('question')
    op.drop_table('form')
    # ### end Alembic commands ###
