"""empty message

Revision ID: ed7f9ea5eff0
Revises: db8f41ac18e1
Create Date: 2021-08-21 12:25:15.386106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7f9ea5eff0'
down_revision = 'db8f41ac18e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('from', sa.Column('questionField', sa.String(length=255), nullable=True))
    op.add_column('from', sa.Column('responseField', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('from', 'responseField')
    op.drop_column('from', 'questionField')
    # ### end Alembic commands ###
