"""empty message

Revision ID: f0bbd8db7b93
Revises: 1560213b0364
Create Date: 2021-08-19 18:06:47.127582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bbd8db7b93'
down_revision = '1560213b0364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('takesEx',
    sa.Column('idExTaken', sa.Integer(), nullable=False),
    sa.Column('idEx', sa.Integer(), nullable=False),
    sa.Column('ciPa', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ciPa'], ['patient.ci'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idEx'], ['exam.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idExTaken', 'idEx', 'ciPa')
    )
    op.create_table('assistsSurg',
    sa.Column('idTakenSurg', sa.Integer(), nullable=False),
    sa.Column('idSurg', sa.Integer(), nullable=False),
    sa.Column('ciPa', sa.Integer(), nullable=False),
    sa.Column('ciMa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ciMa'], ['medicalAssistant.ci'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idTakenSurg', 'idSurg', 'ciPa'], ['takesSurg.idTakenSurg', 'takesSurg.idSurg', 'takesSurg.ciPa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idTakenSurg', 'idSurg', 'ciPa', 'ciMa')
    )
    op.create_table('handlesSurg',
    sa.Column('idTakenSurg', sa.Integer(), nullable=False),
    sa.Column('idSurg', sa.Integer(), nullable=False),
    sa.Column('ciPa', sa.Integer(), nullable=False),
    sa.Column('ciDoc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ciDoc'], ['doctor.ci'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idTakenSurg', 'idSurg', 'ciPa'], ['takesSurg.idTakenSurg', 'takesSurg.idSurg', 'takesSurg.ciPa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idTakenSurg', 'idSurg', 'ciPa', 'ciDoc')
    )
    op.create_table('apRefExam',
    sa.Column('idAp', sa.Integer(), nullable=False),
    sa.Column('ciPaAp', sa.Integer(), nullable=False),
    sa.Column('idExTaken', sa.Integer(), nullable=False),
    sa.Column('idEx', sa.Integer(), nullable=False),
    sa.Column('ciPaEx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idAp', 'ciPaAp'], ['attendsTo.idAp', 'attendsTo.ciPa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idExTaken', 'idEx', 'ciPaEx'], ['takesEx.idExTaken', 'takesEx.idEx', 'takesEx.ciPa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idAp', 'ciPaAp', 'idExTaken', 'idEx', 'ciPaEx')
    )
    op.create_table('apRefTr',
    sa.Column('idAp', sa.Integer(), nullable=False),
    sa.Column('ciPaAp', sa.Integer(), nullable=False),
    sa.Column('idFollows', sa.Integer(), nullable=False),
    sa.Column('idTreatment', sa.Integer(), nullable=False),
    sa.Column('ciPaTr', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idAp', 'ciPaAp'], ['attendsTo.idAp', 'attendsTo.ciPa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idFollows', 'idTreatment', 'ciPaTr'], ['follows.idFollows', 'follows.idTreatment', 'follows.ciPa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idAp', 'ciPaAp', 'idFollows', 'idTreatment', 'ciPaTr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apRefTr')
    op.drop_table('apRefExam')
    op.drop_table('handlesSurg')
    op.drop_table('assistsSurg')
    op.drop_table('takesEx')
    # ### end Alembic commands ###
