"""empty message

Revision ID: f40ef77e2d99
Revises: e6581c9b3aec
Create Date: 2021-08-16 20:32:49.070315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40ef77e2d99'
down_revision = 'e6581c9b3aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('OK', 'CANCELLED', 'RESCHEDULING', name='appointmentState'), nullable=True),
    sa.PrimaryKeyConstraint('ID', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    # ### end Alembic commands ###
