"""empty message

Revision ID: f4d3770062fd
Revises: f40ef77e2d99
Create Date: 2021-08-16 21:53:38.371504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4d3770062fd'
down_revision = 'f40ef77e2d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('phoneNumber', sa.VARCHAR(length=64), nullable=False),
    sa.Column('location', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clinical_sign',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('disease',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exam',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('preview', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('indication',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('laboratory',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('phoneNumber', sa.VARCHAR(length=64), nullable=False),
    sa.Column('location', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=256), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('manufacturer',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('location', sa.VARCHAR(length=256), nullable=True),
    sa.Column('email', sa.VARCHAR(length=256), nullable=True),
    sa.Column('phoneNumber', sa.VARCHAR(length=32), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('medicine',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parameter',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('measureUnit', sa.String(), nullable=True),
    sa.Column('refMinValue', sa.Float(), nullable=True),
    sa.Column('refMaxValue', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('surgery',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('symptom',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('treatment',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('preview', sa.String(), nullable=True),
    sa.Column('indications', sa.JSON(), nullable=True),
    sa.Column('avgSessionTime', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vaccine',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('validity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('diseaseCat',
    sa.Column('IDDisease', sa.Integer(), nullable=False),
    sa.Column('IDCat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IDCat'], ['category.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['IDDisease'], ['disease.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('IDDisease', 'IDCat')
    )
    op.create_table('exHasInd',
    sa.Column('IDEx', sa.Integer(), nullable=False),
    sa.Column('IDInd', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IDEx'], ['exam.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['IDInd'], ['indication.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('IDEx', 'IDInd')
    )
    op.create_table('exHasPar',
    sa.Column('IDEx', sa.Integer(), nullable=False),
    sa.Column('IDPar', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IDEx'], ['exam.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['IDPar'], ['parameter.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('IDEx', 'IDPar')
    )
    op.create_table('manufacturedBy',
    sa.Column('IDMed', sa.Integer(), nullable=False),
    sa.Column('IDManufacturer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IDManufacturer'], ['manufacturer.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['IDMed'], ['medicine.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('IDMed', 'IDManufacturer')
    )
    op.add_column('appointment', sa.Column('timeBegins', sa.Time(), nullable=True))
    op.add_column('appointment', sa.Column('timeEnds', sa.Time(), nullable=True))
    op.add_column('appointment', sa.Column('ETPP', sa.Integer(), nullable=True))
    op.add_column('appointment', sa.Column('maxTurns', sa.Integer(), nullable=True))
    op.alter_column('appointment', 'state',
               existing_type=postgresql.ENUM('OK', 'CANCELLED', 'RESCHEDULING', name='appointmentState'),
               nullable=False)
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.alter_column('appointment', 'state',
               existing_type=postgresql.ENUM('OK', 'CANCELLED', 'RESCHEDULING', name='appointmentState'),
               nullable=True)
    op.drop_column('appointment', 'maxTurns')
    op.drop_column('appointment', 'ETPP')
    op.drop_column('appointment', 'timeEnds')
    op.drop_column('appointment', 'timeBegins')
    op.drop_table('manufacturedBy')
    op.drop_table('exHasPar')
    op.drop_table('exHasInd')
    op.drop_table('diseaseCat')
    op.drop_table('vaccine')
    op.drop_table('treatment')
    op.drop_table('symptom')
    op.drop_table('surgery')
    op.drop_table('parameter')
    op.drop_table('medicine')
    op.drop_table('manufacturer')
    op.drop_table('laboratory')
    op.drop_table('indication')
    op.drop_table('exam')
    op.drop_table('disease')
    op.drop_table('clinical_sign')
    op.drop_table('category')
    op.drop_table('branch')
    # ### end Alembic commands ###
