"""empty message

Revision ID: f93f7f5de771
Revises: ff6a39cef89c
Create Date: 2021-08-27 13:44:35.209413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93f7f5de771'
down_revision = 'ff6a39cef89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('requiresEx_idExTaken_idEx_ciPaEx_fkey', 'requiresEx', type_='foreignkey')
    op.create_foreign_key(None, 'requiresEx', 'exam', ['idEx'], ['id'], ondelete='CASCADE')
    op.drop_column('requiresEx', 'ciPaEx')
    op.drop_column('requiresEx', 'idExTaken')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requiresEx', sa.Column('idExTaken', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('requiresEx', sa.Column('ciPaEx', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'requiresEx', type_='foreignkey')
    op.create_foreign_key('requiresEx_idExTaken_idEx_ciPaEx_fkey', 'requiresEx', 'takesEx', ['idExTaken', 'idEx', 'ciPaEx'], ['idExTaken', 'idEx', 'ciPa'], ondelete='CASCADE')
    # ### end Alembic commands ###
