"""empty message

Revision ID: ff6a39cef89c
Revises: ed7f9ea5eff0
Create Date: 2021-08-25 17:41:33.316819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6a39cef89c'
down_revision = 'ed7f9ea5eff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registersSt',
    sa.Column('ciPa', sa.Integer(), nullable=False),
    sa.Column('idState', sa.Integer(), nullable=False),
    sa.Column('fromDate', sa.DateTime(), nullable=False),
    sa.Column('toDate', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['ciPa'], ['patient.ci'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idState'], ['state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ciPa', 'idState', 'fromDate')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registersSt')
    op.drop_table('state')
    # ### end Alembic commands ###
